name: Build master

on: [push, pull_request]

jobs:
  strategy:
    matrix:
      os: [ubuntu-latest, windows-latest, macOS-latest]
  build:
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build
      run: dotnet build -c Release

  test_cpu:
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
    - name: Run tests
      run: dotnet test

  test_pocl:
    needs: test_cpu
    runs-on: ubuntu_latest
    steps:
    - name: Setup POCL and clinfo 
      run: |
         sudo apt-get update
         sudo apt-get install -y pocl-opencl-icd clinfo
    
    - name: Check OpenCL
      run: clinfo
